spring:
  # rabbit mq
  rabbitmq:
    host: 116.204.76.47
    port: 5672
    username: zs
    password: Cx.123456
    virtual-host: /
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.204.76.47:3306/Chat_database
    username: root
    password: Cx.123456
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# 端口
server:
  port: 8080

# 代码解释器服务地址
python:
  executor:
    url: http://10.211.55.2:8000/execute

# http代理地址
proxy:
  host: 127.0.0.1
  port: 8118

# openAI 的API tokens
openai:
  token: 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
