spring:
  # rabbit mq
  rabbitmq:
    host: 0.0.0.0
    port: 5672
    username: zs
    password: no
    virtual-host: /
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://0.0.0.0:3306/Chat_database
    username: no
    password: no
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# 端口
server:
  port: 8080

# 代码解释器服务地址
python:
  executor:
    url: http://10.211.55.2:8000/execute

# 代理地址
proxy:
  host: 127.0.0.1
  port: 1111

# openAI 的API tokens
openai:
  token: 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
